name: Builder

on:
  push:
    branches: main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: reposotory cloning
      uses: actions/checkout@v1
      
    - name: log dir
      run: ls -la
